//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_log
    {
        public long id { get; set; }
        public long id_project { get; set; }
        public string who_activity { get; set; }
        public System.DateTime date_update { get; set; }
        public string content_update { get; set; }
    
        public virtual project project { get; set; }
    }
}
