//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.projects = new HashSet<project>();
        }
    
        public long id { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string representative { get; set; }
        public string email_of_representative { get; set; }
        public string skype_of_representative { get; set; }
        public string phone_number_of_representative { get; set; }
    
        public virtual ICollection<project> projects { get; set; }
    }
}
