//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class end_project
    {
        public long id { get; set; }
        public string difficulty { get; set; }
        public string advantage { get; set; }
        public string risk { get; set; }
        public string experience { get; set; }
        public Nullable<int> is_fail { get; set; }
    
        public virtual project project { get; set; }
    }
}
