//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quality
    {
        public long id { get; set; }
        public Nullable<int> number_kloc { get; set; }
        public Nullable<int> number_bug_of_team { get; set; }
        public Nullable<int> number_bug_of_team_in_kloc { get; set; }
        public Nullable<int> number_bug_of_customer { get; set; }
        public Nullable<int> number_bug_of_customer_int_kloc { get; set; }
        public Nullable<int> number_test_case { get; set; }
        public Nullable<int> human_resource { get; set; }
        public Nullable<int> time_complete { get; set; }
    
        public virtual project project { get; set; }
    }
}
