//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_project
    {
        public type_project()
        {
            this.projects = new HashSet<project>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string country { get; set; }
    
        public virtual ICollection<project> projects { get; set; }
    }
}
