//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PQM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class activity_log
    {
        public long id { get; set; }
        public long id_project { get; set; }

        [Display(Name = "Người chỉnh sửa")]
        public string who_activity { get; set; }

        [Display(Name = "Thời điểm")]
        public System.DateTime date_update { get; set; }

        [Display(Name = "Nội dung")]
        public string content_update { get; set; }
    
        public virtual project project { get; set; }
    }
}
