//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PQM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class customer
    {
        public customer()
        {
            this.projects = new HashSet<project>();
        }
    
        public long id { get; set; }

        [Required]
        [Display(Name = "Tên công ty")]
        public string company { get; set; }

        [Display(Name = "Địa chỉ")]
        public string address { get; set; }

        [Display(Name = "Đại diện")]
        public string representative { get; set; }

        [Display(Name = "Email")]
        public string email_of_representative { get; set; }

        [Display(Name = "Skype")]
        public string skype_of_representative { get; set; }

        [Display(Name = "Điện thoại")]
        public string phone_number_of_representative { get; set; }
    
        public virtual ICollection<project> projects { get; set; }
    }
}
