//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PQM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class end_project
    {
        public long id { get; set; }

        [Display(Name = "Những khó khăn của dự án")]
        public string difficulty { get; set; }

        [Display(Name = "Thuận lợi")]
        public string advantage { get; set; }

        [Display(Name = "Rủi ro")]
        public string risk { get; set; }

        [Display(Name = "Kinh nghiệm")]
        public string experience { get; set; }

        [Display(Name = "Thành công hay không?")]
        public Nullable<int> is_fail { get; set; }
    
        public virtual project project { get; set; }
    }
}
