//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PQM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class project
    {
        public project()
        {
            this.activity_log = new HashSet<activity_log>();
            this.teams = new HashSet<team>();
        }
    
        public long id { get; set; }

        [Required]
        [Display(Name = "Khách hàng")]
        public long id_customer { get; set; }

        [Required]
        [Display(Name = "Loại dự án")]
        public long id_type_project { get; set; }
        
        [Required]
        [Display(Name = "Tên dự án")]
        public string name_project { get; set; }

        [Required]
        [Display(Name = "Ngày bắt đầu (dự kiến)")]
        public System.DateTime expected_start_date { get; set; }

        [Required]
        [Display(Name = "Ngày kết thúc (dự kiến)")]
        public System.DateTime expected_end_date { get; set; }

        [Display(Name = "Ngày bắt đầu (thực tế)")]
        public Nullable<System.DateTime> actual_start_date { get; set; }

        [Display(Name = "Ngày kết thúc (thực tế)")]
        public Nullable<System.DateTime> actual_end_date { get; set; }

        [Display(Name = "Công nghệ")]
        public string technology { get; set; }

        [Display(Name = "Mục đích")]
        public string purpose { get; set; }

        [Display(Name = "Người đánh giá")]
        public string estimator { get; set; }

        [Display(Name = "Quy mô đánh giá (man/month)")]
        public Nullable<int> scale_estimator { get; set; }

        [Display(Name = "Giá trị hợp đồng")]
        public Nullable<int> contract_value { get; set; }

        [Display(Name = "Quản lý dự án")]
        public string pm { get; set; }

        [Display(Name = "Kỹ sư cầu nối")]
        public string brse { get; set; }

        [Display(Name = "Chi phí hiện tại")]
        public Nullable<int> current_cost { get; set; }

        [Display(Name = "Chi phí ước tính")]
        public Nullable<int> estimated_cost { get; set; }

        [Display(Name = "Phần mềm")]
        public string software { get; set; }

        [Display(Name = "Phần cứng")]
        public string hardware { get; set; }
    
        public virtual ICollection<activity_log> activity_log { get; set; }
        public virtual customer customer { get; set; }
        public virtual end_project end_project { get; set; }
        public virtual type_project type_project { get; set; }
        public virtual quality quality { get; set; }
        public virtual ICollection<team> teams { get; set; }
    }
}
