//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PQM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class quality
    {
        public long id { get; set; }

        [Display(Name = "Số dòng")]
        public Nullable<int> number_kloc { get; set; }

        [Display(Name = "Số lỗi")]
        public Nullable<int> number_bug_of_team { get; set; }

        [Display(Name = "Số lỗi/dòng")]
        public Nullable<int> number_bug_of_team_in_kloc { get; set; }

        [Display(Name = "Số lỗi KH báo")]
        public Nullable<int> number_bug_of_customer { get; set; }

        [Display(Name = "Số lỗi/dòng KH báo")]
        public Nullable<int> number_bug_of_customer_int_kloc { get; set; }

        [Display(Name = "Số kịch bản kiểm thử")]
        public Nullable<int> number_test_case { get; set; }

        [Display(Name = "Số lượng nhân sự")]
        public Nullable<int> human_resource { get; set; }

        [Display(Name = "Tổng thời gian hoàn thành")]
        public Nullable<int> time_complete { get; set; }
    
        public virtual project project { get; set; }
    }
}
