//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PQM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class staff
    {
        public staff()
        {
            this.teams = new HashSet<team>();
        }
    
        public long id { get; set; }

        [Required]
        [Display(Name = "Tên")]
        public string name { get; set; }

        [Display(Name = "Vị trí")]
        public string role { get; set; }

        [Display(Name = "Skype")]
        public string skype { get; set; }

        [Display(Name = "Điện thoại")]
        public string phone_number { get; set; }
    
        public virtual ICollection<team> teams { get; set; }
    }
}
